// demo-components/react/Checkbox.tsx
import { CheckCircle2 } from "lucide-react";
import '../styles/Checkbox.scss';

type CheckboxProps = {
  value: boolean;
  onChange: (value: boolean) => void;
  children?: React.ReactNode;
};

const Checkbox: React.FC<CheckboxProps> = ({
  value,
  onChange,
  children,
}) => {

  return (
    <div className="turtle-panes__checkbox">
      <input type="checkbox" checked={value} onChange={(e) => onChange(e.target.checked)} />
      <CheckCircle2 />
      <span>{children}</span>
    </div>
  );
};

export default Checkbox;

// demo-components/vue/Checkbox.vue
<template>
  <div class="turtle-panes__checkbox">
    <input
      type="checkbox"
      :checked="modelValue"
      @click="
        emit('update:modelValue', ($event.target as HTMLInputElement).checked)
      "
    />
    <CheckCircle2 />
    <span>
      <slot></slot>
    </span>
  </div>
</template>
<script setup lang="ts">
import { CheckCircle2 } from "lucide-vue-next";
const { modelValue } = defineProps(["modelValue"]);
const emit = defineEmits(["update:modelValue"]);
</script>
<style lang="scss" src="../styles/Checkbox.scss">
</style>
