// demo-components/react/DemoDivider.tsx
import { ChevronLeft, ChevronRight } from "lucide-react";
import "../styles/DemoDivider.scss";

const DemoDivider: React.FC = () => {
  return (
    <div className="turtle-panes__demo-divider">
        <div className="turtle-panes__demo-divider-divider">
          <ChevronLeft />
          <ChevronRight />
        </div>
    </div>
  );
};

export default DemoDivider;

// demo-components/vue/DemoDivider.vue
<template>
    <div class="turtle-panes__demo-divider">
        <div class="turtle-panes__demo-divider-divider">
          <ChevronLeft />
          <ChevronRight />
        </div>
    </div>
</template>
<script setup lang="ts">
import { ChevronLeft, ChevronRight } from "lucide-vue-next";
</script>
<style lang="scss" src="../styles/DemoDivider.scss">
</style>
