// demo-components/react/FrameworkSupport.tsx
import Section from "./Section.tsx";
import { SiReact, SiVuedotjs } from "react-icons/si";
import '../styles/FrameworkSupport.scss';

const FrameWorkSupport: React.FC = () => {
  return (
    <Section
      style={{ backgroundColor: "var(--white)" }}
      contentStyle={{ alignItems: "center" }}
    >
      <div
        className="turtle-panes__section-description"
      >
        <h1 className="turtle-panes__heading">Framework support</h1>
        <p className="turtle-panes__description">
          Turtle-Panes plays nicely with some of the major frameworks
        </p>
      </div>
      <div className="demo-framework-support__icons">
        < SiVuedotjs />
        < SiReact />
      </div>
    </Section>
  );
};

export default FrameWorkSupport;

// demo-components/vue/FrameworkSupport.vue
<template>
  <Section
    contentStyle="align-items: center;"
  >
    <div
      class="turtle-panes__section-description"
    >
      <h1 class="turtle-panes__heading">Framework support</h1>
      <p class="turtle-panes__description">
        Turtle-Panes plays nicely with some of the major frameworks
      </p>
    </div>
    <div class="demo-framework-support__icons">
      <a class="demo-intro__button" href="/vue/getting-started">
        <VueDotjsIcon />
        <span>Vue Docs</span>
      </a>
      <a class="demo-intro__button" href="/react/getting-started">
        <ReactIcon />
        <span>React Docs</span>
      </a>
    </div>
  </Section>
</template>
<script setup lang="ts">
import { ReactIcon, VueDotjsIcon } from "vue3-simple-icons";
import Section from "./Section.vue";
</script>
<style lang="scss" src="../styles/FrameworkSupport.scss"></style>
