// demo-components/react/HideDemo.tsx
import Panes from "@turtle-panes/react";
import '@turtle-panes/react/style'

import Section from "./Section.tsx";
import type { ExposedFunctions } from "../../packages/core/src/types/index.ts";
import { useRef, useState } from "react";
import "../styles/HideDemo.scss";

const HideDemo: React.FC = () => {
  const turtlePanesRef = useRef<ExposedFunctions | null>(null);
  const [isPaneHidden, setIsPaneHidden] = useState(false);

  const panesStyle = {
    margin: "40px 0px",
    borderRadius: "20px",
  };

  return (
    <Section contentStyle={{ alignItems: "flex-start" }}>
      <div
        className="turtle-panes__section-description"
        style={{ color: "white" }}
      >
        <h1 className="turtle-panes__heading">Or maybe hide it?</h1>
        <p className="turtle-panes__description">
          Once a pane reaches its min-width, you can also choose to hide it.
        </p>
        <button
          onClick={() => turtlePanesRef.current?.reShowPane(1)}
          style={{ opacity: isPaneHidden ? 1 : 0 }}
        >
          Reset
        </button>
      </div>
      <Panes
        ref={turtlePanesRef}
        style={panesStyle}
        onPanesHidden={(hiddenPaneIds) =>
          setIsPaneHidden(!!hiddenPaneIds?.length)
        }
      >
        <Panes.Pane minWidth={120} hideOnMinWidthExceeded>
          <div className="turtle-panes__demo-box">
            <p>If you don’t want me I’ll just leave</p>
          </div>
        </Panes.Pane>
        <Panes.Pane minWidth={100}>
          <div className="turtle-panes__demo-box">
            <p>My min width is very important to me</p>
          </div>
        </Panes.Pane>
      </Panes>
    </Section>
  );
};

export default HideDemo;

// demo-components/vue/HideDemo.vue
<template>
  <Section
    contentStyle="align-items: flex-start;"
  >
    <div
      class="turtle-panes__section-description"
    >
      <h1 class="turtle-panes__heading">Or maybe hide it ?</h1>
      <p class="turtle-panes__description">
        Once a pane reaches its min-width,<br>you can also choose to hide it
      </p>
      <div class="demo-intro__source-code">
          <a :href="examplesUrl.react"><ReactIcon /> </a>
          <a :href="examplesUrl.vue"><VueIcon /> </a>
      </div>
    </div>
    <TurtlePanes
      ref="turtlePanesRef"
      style="margin: 40px 0px; border-radius: 20px"
    >
      <TurtlePane :min-width="120" :hide-on-min-width-exceeded="true">
        <div class="turtle-panes__demo-box">
          <p>If you don’t want me I’ll just leave</p>
        </div>
      </TurtlePane>
      <TurtlePane :min-width="100" style="align-self: stretch">
        <div class="turtle-panes__demo-box">
          <p>My min width is very important to me</p>
        </div>
      </TurtlePane>
    </TurtlePanes>
    <button
        @click="turtlePanesRef?.reShowPane(1)"
        :style="{ opacity: showResetPaneButton ? 1 : 0 }"
        class="demo-intro__button"
      >
        Reset
      </button>
  </Section>
</template>
<script setup lang="ts">
import { TurtlePanes, TurtlePane } from "@turtle-panes/vue";
import "@turtle-panes/vue/style";
import Section from "./Section.vue";
import { ref, computed } from "vue";
import type { ExposedFunctions } from "../../packages/core/src/types";
import { ReactIcon, VueDotjsIcon as VueIcon } from "vue3-simple-icons";

const turtlePanesRef = ref<ExposedFunctions | null>(null);

const showResetPaneButton = computed(() => {
  return !!turtlePanesRef.value?.hiddenPanes().length;
});

const examplesUrl = {
  react: `${import.meta.env.VITE_GITHUB_EXAMPLES_REPO}/react/HideDemo.tsx`,
  vue: `${import.meta.env.VITE_GITHUB_EXAMPLES_REPO}/vue/HideDemo.vue`,
}
</script>
