// demo-components/vue/CustomDividerDemo.vue
<template>
  <Section
    contentStyle="align-items: flex-start;"
  >
    <div
      class="turtle-panes__section-description"
    >
      <h1 class="turtle-panes__heading">Custom divider ?</h1>
      <p class="turtle-panes__description">We got you covered.</p>
      <div class="demo-intro__source-code">
          <a :href="examplesUrl.react"><ReactIcon /> </a>
          <a :href="examplesUrl.vue"><VueIcon /> </a>
      </div>
    </div>
    <TurtlePanes
      style="
        margin: 20px 0px;
        border-radius: 20px;
        background-color: var(--white);
      "
    >
      <TurtlePane>
        <div style="width: 30cqw" class="turtle-panes__demo-box"></div>
        <template v-slot:divider>
          <div class="turtle-panes__custom-divider">🐢</div>
        </template>
      </TurtlePane>
      <TurtlePane>
        <div style="width: 30cqw" class="turtle-panes__demo-box"></div>
        <template v-slot:divider>
          <div class="turtle-panes__custom-divider">🏎️</div>
        </template>
      </TurtlePane>
      <TurtlePane>
        <div style="width: 30cqw" class="turtle-panes__demo-box"></div>
      </TurtlePane>
    </TurtlePanes>
  </Section>
</template>
<script setup lang="ts">
import { TurtlePanes, TurtlePane } from "@turtle-panes/vue";
import "@turtle-panes/vue/style";
import Section from "./Section.vue";
import { ReactIcon, VueDotjsIcon as VueIcon } from "vue3-simple-icons";
const examplesUrl = {
  react: `${import.meta.env.VITE_GITHUB_EXAMPLES_REPO}/react/CustomDividerDemo.tsx`,
  vue: `${import.meta.env.VITE_GITHUB_EXAMPLES_REPO}/vue/CustomDividerDemo.vue`,
}
</script>
<style lang="scss" src="../styles/CustomDividerDemo.scss">
</style>

// demo-components/react/CustomDividerDemo.tsx
import Panes from "@turtle-panes/react";
import '@turtle-panes/react/style'

import Section from "./Section.tsx";
import '../styles/CustomDividerDemo.scss';

const CustomDividerDemo: React.FC = () => {
  const panesStyle = {
    margin: "20px 0px",
    borderRadius: "20px",
    backgroundColor: "var(--white)",
    height: "40cqw",
  };


  const divWidth =  {
    width: "30cqw",
  }

  return (
    <Section
      contentStyle={{ alignItems: "flex-start" }}
    >
      <div
        className="turtle-panes__section-description"
      >
        <h1 className="turtle-panes__heading">Custom divider ?</h1>
        <p className="turtle-panes__description">We got you covered.</p>
      </div>
      <Panes style={panesStyle}>
        <Panes.Pane
          divider={
            <Panes.Divider>
              {" "}
              <div className="turtle-panes__custom-divider">🐢</div>
            </Panes.Divider>
          }
        >
          <div
            style={divWidth}
            className="turtle-panes__demo-box"
          ></div>
        </Panes.Pane>
        <Panes.Pane
          divider={
            <Panes.Divider>
              {" "}
              <div className="turtle-panes__custom-divider">🏎️</div>
            </Panes.Divider>
          }
        >
          <div
            style={divWidth}
            className="turtle-panes__demo-box"
          ></div>
        </Panes.Pane>
        <Panes.Pane>
          <div
            style={divWidth}
            className="turtle-panes__demo-box"
          ></div>
        </Panes.Pane>
      </Panes>
    </Section>
  );
};

export default CustomDividerDemo;
